title: "Bird Sightings at Sea"
article:
  title: "At-Sea Observations of Seabirds 1969 to 1990, Tasman Sea, New Zealand and Australian waters"
  url: "https://obis.org/dataset/29ea15ed-8f76-40ca-bd14-58c62e10b2ef"
data_source:
  title: "At-Sea Observations of Seabirds 1969 to 1990"
  url: "https://catalogue.data.govt.nz/dataset/at-sea-observations-of-seabirds-1969-to-1990"
credit:
  post: "Tarun Yadav"
  github: "@whytarunishere"
